// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCThBrciDb1V-YqHhHsB6PUsLwSaT-fXHA',
    appId: '1:718245823939:web:f3e9164fcff01608baa976',
    messagingSenderId: '718245823939',
    projectId: 'myloginapplication-12be7',
    authDomain: 'myloginapplication-12be7.firebaseapp.com',
    storageBucket: 'myloginapplication-12be7.appspot.com',
    measurementId: 'G-4WZZMSMMSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYe4K-CN3AuElag601z2TDHzzF4-maIu4',
    appId: '1:718245823939:android:d53e2a04e1fe29c8baa976',
    messagingSenderId: '718245823939',
    projectId: 'myloginapplication-12be7',
    storageBucket: 'myloginapplication-12be7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPMk0XeKQMlvZ0_DZsT83COxJ9RVrwY3Y',
    appId: '1:718245823939:ios:60cebfa8ebd71261baa976',
    messagingSenderId: '718245823939',
    projectId: 'myloginapplication-12be7',
    storageBucket: 'myloginapplication-12be7.appspot.com',
    iosClientId: '718245823939-g5rf6slie5ge2u0js7nutk1mbm9o30ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPMk0XeKQMlvZ0_DZsT83COxJ9RVrwY3Y',
    appId: '1:718245823939:ios:60cebfa8ebd71261baa976',
    messagingSenderId: '718245823939',
    projectId: 'myloginapplication-12be7',
    storageBucket: 'myloginapplication-12be7.appspot.com',
    iosClientId: '718245823939-g5rf6slie5ge2u0js7nutk1mbm9o30ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
